services:
  dev-db:
    image: mongo:8
    environment:
      MONGO_INITDB_ROOT_USERNAME: sewkito
      MONGO_INITDB_ROOT_PASSWORD: 123
      MONGO_INITDB_DATABASE: zof
    ports:
      - '27018:27017'
    networks:
      - zof
    volumes:
      - mongodb_dev_data:/data/db
    healthcheck:
      test: ['CMD', 'mongosh', '--eval', 'db.runCommand("ping").ok']
      interval: 5s
      timeout: 5s
      retries: 5

  mongo-express:
    image: mongo-express:1.0
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://sewkito:123@dev-db:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    ports:
      - '8080:8081'
    networks:
      - zof
    depends_on:
      dev-db:
        condition: service_healthy

  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
    networks:
      - zof
    volumes:
      - redis_dev_data:/data

  test-redis:
    image: redis:7-alpine
    ports:
      - '6380:6379'
    networks:
      - zof

networks:
  zof:
    driver: bridge

volumes:
  mongodb_dev_data:
  redis_dev_data:
