### GET request
GET http://localhost:8000/api/v1/users

### POST request
POST http://localhost:3000/api/v1/auth/register
Content-Type: application/json

{
    "firstName": "Aboki",
    "lastName": "Nkemakolam",
    "email": "skey@mail.co",  
    "terms_of_service": true,
    "password":"Password123!"
}
