### GET request
GET http://localhost:8000/api/v1/users

### POST request
POST http://localhost:8000/api/v1/auth/register
Content-Type: application/json

{
    "firstName": "Aboki",
    "lastName": "Nkemakolam",
    "email": "skey@mail.co",  
    "terms_of_service": true,
    "password":"Password123!"
}

### POST request
POST http://localhost:8000/api/v1/blogs
Content-Type: application/json

{
    "title": "Become A Fullstack Web Dev In 1 Week",
    "desc": "Do you aspire to become an ondemand fullstack webdevelper? Then this is the opportunity for you. Get onboard with our 1 week long training bootcamp to get started.",
    "banner": "imageUrl",  
    "draft": false,
    "featured":true,
    "content":{"blocks": [{"id":"blog id", "type":"header"}]}
}
