export const NODE_ENV = 'NODE_ENV';

export const PORT = 'PORT';

export const DATABASE_URL = 'DATABASE_URL';

export const VERSION = 'VERSION';

export const REDIS_CLOUD_URL = 'REDIS_CLOUD_URL';

export const BASE_URL = 'BASE_URL';

export const ALLOWED_EMAILS = 'ALLOWED_EMAILS';

export const JWT_ACCESS_TOKEN_SECRET = 'JWT_ACCESS_TOKEN_SECRET';

export const JWT_REFRESH_TOKEN_SECRET = 'JWT_REFRESH_TOKEN_SECRET';

export const JWT_ACCESS_TOKEN_EXP = 'JWT_ACCESS_TOKEN_EXP';

export const JWT_REFRESH_TOKEN_EXP = 'JWT_REFRESH_TOKEN_EXP';

export const CLOUDINARY_CLOUD_NAME = 'CLOUDINARY_CLOUD_NAME';

export const CLOUDINARY_API_KEY = 'CLOUDINARY_API_KEY';

export const CLOUDINARY_API_SECRET = 'CLOUDINARY_API_SECRET';

export const CLOUDINARY_UPLOAD_PRESET = 'CLOUDINARY_UPLOAD_PRESET';

export const GOOGLE_APP_USER = 'GOOGLE_APP_USER';

export const GOOGLE_APP_PASSWORD = 'GOOGLE_APP_PASSWORD';
